# Generated by Django 5.1.6 on 2025-04-26 15:03

from django.db import migrations, models
import datetime
from django.contrib.auth.hashers import make_password

def create_default_users(apps, schema_editor):
    User = apps.get_model('users', 'User')
    Role = apps.get_model('roles', 'Role')

    admin_role = Role.objects.filter(name='Admin').first()
    user_role = Role.objects.filter(name='User').first()

    User.objects.create(
        username='admin',
        email='admin@gmail.com',
        password=make_password('123456'),
        full_name='Administrator',
        gender='Nam',
        date_of_birth=datetime.date(1990, 1, 1),
        role=admin_role
    )

    User.objects.create(
        username='1',
        email='1@gmail.com',
        password=make_password('123456'),
        full_name='Test User',
        gender='Nam',
        date_of_birth=datetime.date(2000, 1, 1),
        role=user_role
    )
    
    User.objects.create(
        username='1',
        email='1@gmail.com',
        password=make_password('123456'),
        full_name='1',
        gender='Nam',
        date_of_birth=datetime.date(1990, 1, 1),
        role=user_role
    )

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(create_default_users),
    ]
