# Generated by Django 5.1.7 on 2025-03-21 16:18

import uuid
from django.db import migrations, models


def create_default_payment_methods(apps, schema_editor):
    PaymentMethod = apps.get_model(
        "payment_methods", "PaymentMethod"
    )  # Đảm bảo 'payments' là tên app
    PaymentMethod.objects.create(name="VNPAY")
    PaymentMethod.objects.create(name="MOMO")
    PaymentMethod.objects.create(name="ZALOPAY")


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "payment_methods",
            },
        ),
        migrations.RunPython(
            create_default_payment_methods
        ),
    ]
