# Generated by Django 5.1.7 on 2025-03-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='duration_days',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
    ]
