# Generated by Django 5.1.6 on 2025-04-05 14:59

from django.db import migrations, models


def create_default_plans(apps, schema_editor):
    Plan = apps.get_model("plans", "Plan")
    Plan.objects.create(
        name="Student",
        price=150000,
        description="Gói sinh viên 3 tháng",
        duration_days=3,
    )
    Plan.objects.create(
        name="Individual",
        price=99000,
        description="1 tài khoản Premium, Hủy bất cứ lúc nào , đăng ký hoặc thanh toán một lần",
        duration_days=5,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0002_plan_duration_days"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="price",
            field=models.IntegerField(),
        ),
        migrations.RunPython(create_default_plans),
    ]
