# Generated by Django 5.1.7 on 2025-05-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_questionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionhistory',
            name='frequency',
            field=models.IntegerField(default=1),
        ),
    ]
