# Generated by Django 5.1.6 on 2025-05-05 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_questionhistory'),
        ('plans', '0005_questionhistory_frequency'),
    ]

    operations = [
    ]
