# Generated by Django 5.1.6 on 2025-05-05 01:00

from django.db import migrations, models


def create_default_plans(apps, schema_editor):
    Plan = apps.get_model("plans", "Plan")
    Plan.objects.create(
        name="Student",
        price=150000,
        description="Gói sinh viên 3 tháng",
        duration_days=3,
    )
    Plan.objects.create(
        name="Individual",
        price=99000,
        description="1 tài khoản Premium, Hủy bất cứ lúc nào , đăng ký hoặc thanh toán một lần",
        duration_days=5,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0006_merge_20250505_0759"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionhistory",
            name="frequency",
            field=models.IntegerField(default=1),
        ),
        migrations.RunPython(create_default_plans),
    ]
