# Generated by Django 5.1.6 on 2025-03-06 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='payment_method_id',
            new_name='payment_method',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='plan_id',
            new_name='plan',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='user_id',
            new_name='user',
        ),
    ]
