# Generated by Django 5.1.6 on 2025-03-10 14:24

import django.db.models.deletion
from django.db import migrations, models

def assign_songs_to_albums(apps, schema_editor):
    Song = apps.get_model('songs', 'Song')
    Album = apps.get_model('albums', 'Album')
    SongAlbum = apps.get_model('songs_album', 'SongAlbum')

    # Lấy tất cả album và bài hát, sắp xếp theo thời gian tạo
    albums = list(Album.objects.order_by('created_at'))
    songs = list(Song.objects.order_by('created_at'))

    song_index = 0
    songs_per_album = 3

    for album in albums:
        for _ in range(songs_per_album):
            if song_index >= len(songs):
                break  # Hết bài hát
            SongAlbum.objects.create(album=album, song=songs[song_index])
            song_index += 1

class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_remove_album_artist'),
        ('songs_album', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songalbum',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_song', to='albums.album'),
        ),
        migrations.RunPython(assign_songs_to_albums),
    ]
