# Generated by Django 5.1.6 on 2025-03-10 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_remove_album_artist'),
        ('songs_album', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songalbum',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_song', to='albums.album'),
        ),
    ]
