# Generated by Django 5.1.7 on 2025-03-21 16:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0002_artist_image'),
        ('songs', '0008_song_image_alter_song_audio_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongArtist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_song', to='artists.artist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_artist', to='songs.song')),
            ],
            options={
                'db_table': 'songs_artist',
            },
        ),
    ]
