# Generated by Django 5.1.7 on 2025-03-21 16:18

import django.db.models.deletion
import uuid
from django.db import migrations, models

def assign_songs_to_artists(apps, schema_editor):
    Artist = apps.get_model('artists', 'Artist')
    Song = apps.get_model('songs', 'Song')
    SongArtist = apps.get_model('songs_artist', 'SongArtist')

    # Lấy tất cả các nghệ sĩ và bài hát, sắp xếp theo thời gian tạo
    artists = list(Artist.objects.order_by('created_at'))
    songs = list(Song.objects.order_by('created_at'))

    artist_index = 0
    artists_count = len(artists)

    for song in songs:
        if artists_count == 0:
            break  # Không có nghệ sĩ nào

        # Lấy nghệ sĩ theo chỉ số và gán cho bài hát
        artist = artists[artist_index]

        # Tạo bản ghi trong bảng trung gian SongArtist
        SongArtist.objects.create(song=song, artist=artist)

        # Cập nhật chỉ số nghệ sĩ để lặp lại nếu cần
        artist_index = (artist_index + 1) % artists_count

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0002_artist_image'),
        ('songs', '0008_song_image_alter_song_audio_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongArtist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_song', to='artists.artist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_artist', to='songs.song')),
            ],
            options={
                'db_table': 'songs_artist',
            },
        ),
        migrations.RunPython(assign_songs_to_artists),
    ]
