# Generated by Django 5.1.6 on 2025-03-09 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0007_remove_song_album_remove_song_artist_and_more'),
        ('songs_artist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songartist',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artists_relation', to='songs.song'),
        ),
    ]
