# Generated by Django 5.1.6 on 2025-03-10 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
        ('songs', '0008_song_image_alter_song_audio_url'),
        ('songs_artist', '0002_alter_songartist_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songartist',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_song', to='artists.artist'),
        ),
        migrations.AlterField(
            model_name='songartist',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_artist', to='songs.song'),
        ),
    ]
