# Generated by Django 5.1.6 on 2025-03-24 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_remove_room_slug_alter_room_name_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Conversation',
        ),
    ]
