# Generated by Django 5.1.6 on 2025-03-06 11:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('message_text', models.TextField()),
                ('file_url', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'chats',
            },
        ),
    ]
