# Generated by Django 5.1.7 on 2025-03-21 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
