# Generated by Django 5.1.6 on 2025-03-06 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follows', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='artist_id',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='user_id',
            new_name='user',
        ),
    ]
