# Generated by Django 5.1.6 on 2025-03-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_rename_artist_id_album_artist'),
        ('artists', '0001_initial'),
        ('songs', '0003_alter_song_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ManyToManyField(related_name='albums', to='albums.album'),
        ),
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.ManyToManyField(related_name='songs', to='artists.artist'),
        ),
    ]
