# Generated by Django 5.1.6 on 2025-03-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0003_rename_user_id_playlist_user'),
        ('songs', '0004_remove_song_album_remove_song_artist_song_album_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='playlist',
            field=models.ManyToManyField(related_name='playlists', to='playlists.playlist'),
        ),
    ]
