# Generated by Django 5.1.6 on 2025-03-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_rename_artist_id_album_artist'),
        ('playlists', '0003_rename_user_id_playlist_user'),
        ('songs', '0005_song_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ManyToManyField(blank=True, related_name='albums', to='albums.album'),
        ),
        migrations.AlterField(
            model_name='song',
            name='playlist',
            field=models.ManyToManyField(blank=True, related_name='playlists', to='playlists.playlist'),
        ),
    ]
