# Generated by Django 5.1.6 on 2025-03-10 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0007_remove_song_album_remove_song_artist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
