# Generated by Django 5.1.6 on 2025-05-03 12:22

from django.db import migrations, models
import datetime


def create_default_songs(apps, schema_editor):
    Song = apps.get_model('songs', 'Song')
    Category = apps.get_model('categories', 'Category')

    # Lấy genre mẫu (nếu có)
    try:
        genre = Category.objects.first()
    except:
        genre = None

    Song.objects.create(
        title='Nơi tình yêu kết thúc',
        genre=genre,
        duration=318,
        release_date=datetime.date(2023, 1, 1),
        image='https://i.ytimg.com/vi/4S0jwsH7WYw/maxresdefault.jpg',
        audio_url='https://res.cloudinary.com/dwo0sby8p/video/upload/v1746966944/cwp8d6z4ffg5hd3drh9l.mp3',
        video_url='https://res.cloudinary.com/dwo0sby8p/video/upload/v1746966952/ih1by8ycbdreyaxo4jfu.webm'
    )
    Song.objects.create(
        title='Nơi này có anh',
        genre=genre,
        duration=260,
        release_date=datetime.date(2023, 1, 2),
        image='https://i.ytimg.com/vi/FN7ALfpGxiI/maxresdefault.jpg',
        audio_url='https://res.cloudinary.com/dwo0sby8p/video/upload/v1746967223/hjq2hhjesgamfjtm4dha.mp3',
        video_url='https://res.cloudinary.com/dwo0sby8p/video/upload/v1746967230/iim5iwkwk2xpqe85lhvf.webm'
    )
    Song.objects.create(
        title='Dù cho tận thế',
        genre=genre,
        duration=233,
        release_date=datetime.date(2022, 1, 1),
        image='https://cdn.lawnet.vn/uploads/giao-duc/DVM/trang-thue-1300.jpg',
        audio_url='https://res.cloudinary.com/dwo0sby8p/video/upload/v1746967302/sojo2yridsbfnnkadceh.mp3',
        video_url='https://res.cloudinary.com/dwo0sby8p/video/upload/v1746967305/ixgm6pwkkumq7ln6nrmr.webm'
    )
    Song.objects.create(
        title='Một đời',
        genre=genre,
        duration=328,
        release_date=datetime.date(2022, 1, 1),
        image='https://s.meta.com.vn/img/thumb.ashx/Data/image/2020/12/26/loi-bai-hat-dom-dom-jack-1.jpg',
        audio_url='https://res.cloudinary.com/dwo0sby8p/video/upload/v1746967382/ep0hupjx7yx7gsjfj6fb.mp3',
        video_url='https://res.cloudinary.com/dwo0sby8p/video/upload/v1746967385/hmgsgp6tgemibbwi1p0l.webm'
    )
 

    Song.objects.create(
        title='Mất kết nối',
        genre=genre,
        duration=208,
        release_date=datetime.date(2022, 1, 1),
        image='https://tse2.mm.bing.net/th?id=OIP.FUu2bUk5KbVChxd5Rj4DgAHaEK&pid=Api&P=0&h=180',
        audio_url='https://res.cloudinary.com/dwo0sby8p/video/upload/v1746967511/mrhhqnsuwqe2ibsg0he0.mp3',
        video_url='https://res.cloudinary.com/dwo0sby8p/video/upload/v1746967514/qnanctz0apdxs92tdsuh.webm'
    )
    Song.objects.create(
        title='Sau tất cả',
        genre=genre,
        duration=208,
        release_date=datetime.date(2022, 1, 1),
        image='https://i.ytimg.com/vi/wHF3Jv6Gk2o/hqdefault.jpg',
        audio_url='https://res.cloudinary.com/dwo0sby8p/video/upload/v1746967582/bi32wiii6rcy71zy6cux.mp3',
        video_url='https://res.cloudinary.com/dwo0sby8p/video/upload/v1746967587/v8ebtmgei1tpj43tb5pa.webm'
    )
    Song.objects.create(
        title='Nơi ấy con tìm về',
        genre=genre,
        duration=208,
        release_date=datetime.date(2022, 1, 1),
        image='https://img.youtube.com/vi/uvIgpYPAcaQ/hqdefault.jpg',
        audio_url='https://res.cloudinary.com/dwo0sby8p/video/upload/v1746967645/h56l20in5rudoqm5ljy1.mp3',
        video_url='https://res.cloudinary.com/dwo0sby8p/video/upload/v1746967651/vxphdlmooeorbivtdfzt.webm'
    )
    
    Song.objects.create(
        title='Khóa ly biệt',
        genre=genre,
        duration=208,
        release_date=datetime.date(2022, 1, 1),
        image='https://tse3.mm.bing.net/th?id=OIP.d7mQWXHStpY6DbrxP43wrAHaEK&pid=Api&P=0&h=180',
        audio_url='https://res.cloudinary.com/dwo0sby8p/video/upload/v1746967713/sfyqcucsyhz4hn3px380.mp3',
        video_url='https://res.cloudinary.com/dwo0sby8p/video/upload/v1746967719/ydzzfmoj9yjeeg8vkdia.webm'
    )
    
    Song.objects.create(
        title='Sao em vô tình',
        genre=genre,
        duration=208,
        release_date=datetime.date(2022, 1, 1),
        image='https://i.ytimg.com/vi/bI7xde9-3BI/maxresdefault.jpg',
        audio_url='https://res.cloudinary.com/dwo0sby8p/video/upload/v1746967766/a18vuwdbrmikb1ab2fei.mp3',
        video_url='https://res.cloudinary.com/dwo0sby8p/video/upload/v1746967769/el54n6h4auvlmun8sxjl.webm'
    )

    Song.objects.create(
        title='Đi về nhà',
        genre=genre,
        duration=208,
        release_date=datetime.date(2022, 1, 1),
        image='https://tse4.mm.bing.net/th?id=OIP.BV6b1vkah6dMnlCv5R489AHaEK&pid=Api&P=0&h=180',
        audio_url='https://res.cloudinary.com/dwo0sby8p/video/upload/v1746967817/ozwxb53hodmhyc60z0ay.mp3',
        video_url='https://res.cloudinary.com/dwo0sby8p/video/upload/v1746967821/ofzxo9dk2h9pyeywyi1u.webm'
    )
    
    Song.objects.create(
        title='Đừng yêu nữa em mệt rồi',
        genre=genre,
        duration=208,
        release_date=datetime.date(2022, 1, 1),
        image='https://i.ytimg.com/vi/22jqPbfUZBE/maxresdefault.jpg',
        audio_url='https://res.cloudinary.com/dwo0sby8p/video/upload/v1746967868/ltmidqxhuk0j9vrugyrx.mp3',
        video_url='https://res.cloudinary.com/dwo0sby8p/video/upload/v1746967872/qwrixe5k4gusfrxsnuvu.webm'
    )
    
      
    Song.objects.create(
        title='Ấn nút nhớ thả giấc mơ',
        genre=genre,
        duration=208,
        release_date=datetime.date(2022, 1, 1),
        image='https://i.ytimg.com/vi/2jeqQ6Py-o8/maxresdefault.jpg',
        audio_url='https://res.cloudinary.com/dwo0sby8p/video/upload/v1746962630/re5nxu6xfome5vriyitr.mp3',
        video_url='https://res.cloudinary.com/dwo0sby8p/video/upload/v1746962636/u2y0vltwao9nkghhexqi.webm'
    )
    
    Song.objects.create(
        title='Nơi pháo hoa rực rỡ',
        genre=genre,
        duration=208,
        release_date=datetime.date(2022, 1, 1),
        image='https://tse3.mm.bing.net/th?id=OIP.KorsxucNne614rNyuUqPbQAAAA&pid=Api&P=0&h=180',
        audio_url='https://res.cloudinary.com/dwo0sby8p/video/upload/v1746967943/gwdj7ojkmoqqimxuohwk.mp3',
        video_url='https://res.cloudinary.com/dwo0sby8p/video/upload/v1746967947/aucw9ut3mdsdmkdtpmsn.webm'
    )
    
    Song.objects.create(
        title='Đom đóm',
        genre=genre,
        duration=208,
        release_date=datetime.date(2022, 1, 1),
        image='https://s.meta.com.vn/img/thumb.ashx/Data/image/2020/12/26/loi-bai-hat-dom-dom-jack-1.jpg',
        audio_url='https://res.cloudinary.com/dwo0sby8p/video/upload/v1746967990/jqi32grqgvbqd7omeker.mp3',
        video_url='https://res.cloudinary.com/dwo0sby8p/video/upload/v1746967998/ph7q5nuzybelqikotrkn.webm'
    )
    
    Song.objects.create(
        title='Sài Gòn đau lòng quá',
        genre=genre,
        duration=208,
        release_date=datetime.date(2022, 1, 1),
        image='https://i.scdn.co/image/ab67616d0000b2736280a70b22a9778115516eb3',
        audio_url='https://res.cloudinary.com/dwo0sby8p/video/upload/v1746968043/vsdpo0wnt5p7iufleele.mp3',
        video_url='https://res.cloudinary.com/dwo0sby8p/video/upload/v1746968046/jmzf5zwpsfkchffswcg8.webm'
    )
    
    Song.objects.create(
        title='Đường lên phía trước',
        genre=genre,
        duration=208,
        release_date=datetime.date(2022, 1, 1),
        image='https://i.ytimg.com/vi/zX0pOC7y68U/maxresdefault.jpg',
        audio_url='https://res.cloudinary.com/dwo0sby8p/video/upload/v1746968091/bbipxgxuwdwdrub7ph1j.mp3',
        video_url='https://res.cloudinary.com/dwo0sby8p/video/upload/v1746968096/kidrchnlenjuutzovjnu.webm'
    )
    
    
class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0008_song_image_alter_song_audio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.RunPython(create_default_songs),

    ]
