# Generated by Django 5.1.6 on 2025-05-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0008_song_image_alter_song_audio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
