# Generated by Django 5.1.6 on 2025-05-03 12:22

from django.db import migrations, models
import datetime


def create_default_songs(apps, schema_editor):
    Song = apps.get_model('songs', 'Song')
    Category = apps.get_model('categories', 'Category')

    # Lấy genre mẫu (nếu có)
    try:
        genre = Category.objects.first()
    except:
        genre = None

    Song.objects.create(
        title='Nơi tình yêu kết thúc',
        genre=genre,
        duration=318,
        release_date=datetime.date(2023, 1, 1),
        image='https://i.ytimg.com/vi/4S0jwsH7WYw/maxresdefault.jpg',
        audio_url='https://res.cloudinary.com/dneh4yrye/video/upload/v1746503693/hkr755cdntkzhkvdcavj.mp3',
        video_url='https://res.cloudinary.com/dneh4yrye/video/upload/v1746503698/aqjtzb8wm1lzqailbcoc.webm'
    )
    Song.objects.create(
        title='Nơi này có anh',
        genre=genre,
        duration=260,
        release_date=datetime.date(2023, 1, 2),
        image='https://i.ytimg.com/vi/FN7ALfpGxiI/maxresdefault.jpg',
        audio_url='https://res.cloudinary.com/dneh4yrye/video/upload/v1746502295/jyad88xu54aars8wgurs.mp3',
        video_url='https://res.cloudinary.com/dneh4yrye/video/upload/v1746502305/vimrypamspuhqorf1umk.webm'
    )
    Song.objects.create(
        title='Dù cho tận thế',
        genre=genre,
        duration=233,
        release_date=datetime.date(2022, 1, 1),
        image='https://cdn.lawnet.vn/uploads/giao-duc/DVM/trang-thue-1300.jpg',
        audio_url='https://res.cloudinary.com/dneh4yrye/video/upload/v1746350980/lrt5tw2xvxdanxpdqgkz.mp3',
        video_url='https://res.cloudinary.com/dneh4yrye/video/upload/v1746350982/yjj6iqqpavwetuna8jis.webm'
    )
    Song.objects.create(
        title='Một đời',
        genre=genre,
        duration=328,
        release_date=datetime.date(2022, 1, 1),
        image='https://s.meta.com.vn/img/thumb.ashx/Data/image/2020/12/26/loi-bai-hat-dom-dom-jack-1.jpg',
        audio_url='https://res.cloudinary.com/dneh4yrye/video/upload/v1746350887/xjak85x0issl3ieluvkh.mp3',
        video_url='https://res.cloudinary.com/dneh4yrye/video/upload/v1746350892/o8xaxa9k2y4oqjilqz7g.webm'
    )
    
    Song.objects.create(
        title='Một đời',
        genre=genre,
        duration=328,
        release_date=datetime.date(2022, 1, 1),
        image='https://s.meta.com.vn/img/thumb.ashx/Data/image/2020/12/26/loi-bai-hat-dom-dom-jack-1.jpg',
        audio_url='https://res.cloudinary.com/dneh4yrye/video/upload/v1746350887/xjak85x0issl3ieluvkh.mp3',
        video_url='https://res.cloudinary.com/dneh4yrye/video/upload/v1746350892/o8xaxa9k2y4oqjilqz7g.webm'
    )

    Song.objects.create(
        title='Mất kết nối',
        genre=genre,
        duration=208,
        release_date=datetime.date(2022, 1, 1),
        image='https://tse2.mm.bing.net/th?id=OIP.FUu2bUk5KbVChxd5Rj4DgAHaEK&pid=Api&P=0&h=180',
        audio_url='https://res.cloudinary.com/dneh4yrye/video/upload/v1746500916/bdevr54330izqbwlwsff.mp3',
        video_url='https://res.cloudinary.com/dneh4yrye/video/upload/v1746500919/acm1r67e6b3nvjl1tnyt.webm'
    )
    Song.objects.create(
        title='Sau tất cả',
        genre=genre,
        duration=208,
        release_date=datetime.date(2022, 1, 1),
        image='https://i.ytimg.com/vi/wHF3Jv6Gk2o/hqdefault.jpg',
        audio_url='https://res.cloudinary.com/dneh4yrye/video/upload/v1746502811/ejgwkttrxn5vuvsyrrzb.mp3',
        video_url='https://res.cloudinary.com/dneh4yrye/video/upload/v1746502816/toare7raaegesdptvt9r.webm'
    )
    Song.objects.create(
        title='Nơi ấy con tìm về',
        genre=genre,
        duration=208,
        release_date=datetime.date(2022, 1, 1),
        image='https://img.youtube.com/vi/uvIgpYPAcaQ/hqdefault.jpg',
        audio_url='https://res.cloudinary.com/dneh4yrye/video/upload/v1746502041/y1nyqms4eq1elv9nda2x.mp3',
        video_url='https://res.cloudinary.com/dneh4yrye/video/upload/v1746502046/jo15tolrzspz0j1zl1vv.webm'
    )
    
    Song.objects.create(
        title='Khóa ly biệt',
        genre=genre,
        duration=208,
        release_date=datetime.date(2022, 1, 1),
        image='https://tse3.mm.bing.net/th?id=OIP.d7mQWXHStpY6DbrxP43wrAHaEK&pid=Api&P=0&h=180',
        audio_url='https://res.cloudinary.com/dneh4yrye/video/upload/v1746351119/ogxvazfffmjpiod76oqt.mp3',
        video_url='https://res.cloudinary.com/dneh4yrye/video/upload/v1746351125/zdeavmhlfoitymarltw5.webm'
    )
    
    Song.objects.create(
        title='Sao em vô tình',
        genre=genre,
        duration=208,
        release_date=datetime.date(2022, 1, 1),
        image='https://i.ytimg.com/vi/bI7xde9-3BI/maxresdefault.jpg',
        audio_url='https://res.cloudinary.com/dneh4yrye/video/upload/v1746502702/ftydeft1asnxdkocymzi.mp3',
        video_url='https://res.cloudinary.com/dneh4yrye/video/upload/v1746502708/ui6mpsaruaciyuscpnte.webm'
    )

    Song.objects.create(
        title='Đi về nhà',
        genre=genre,
        duration=208,
        release_date=datetime.date(2022, 1, 1),
        image='https://tse4.mm.bing.net/th?id=OIP.BV6b1vkah6dMnlCv5R489AHaEK&pid=Api&P=0&h=180',
        audio_url='https://res.cloudinary.com/dneh4yrye/video/upload/v1746335106/f5r4ptshk1p0y4hcqo4p.mp3',
        video_url='https://res.cloudinary.com/dneh4yrye/video/upload/v1746335111/ebyiavc4m9lkqwt7ebel.webm'
    )
    
    Song.objects.create(
        title='Đừng yêu nữa em mệt rồi',
        genre=genre,
        duration=208,
        release_date=datetime.date(2022, 1, 1),
        image='https://i.ytimg.com/vi/22jqPbfUZBE/maxresdefault.jpg',
        audio_url='https://res.cloudinary.com/dneh4yrye/video/upload/v1746351027/nibtkjxhmgyfij1qicyn.mp3',
        video_url='https://res.cloudinary.com/dneh4yrye/video/upload/v1746351031/zg7xd6fzaqvdimaqagf2.webm'
    )
    
      
    Song.objects.create(
        title='Ấn nút nhớ thả giấc mơ',
        genre=genre,
        duration=208,
        release_date=datetime.date(2022, 1, 1),
        image='https://i.ytimg.com/vi/2jeqQ6Py-o8/maxresdefault.jpg',
        audio_url='https://res.cloudinary.com/dneh4yrye/video/upload/v1746333700/djlmjqljj8c2gmzmpyrk.mp3',
        video_url='https://res.cloudinary.com/dneh4yrye/video/upload/v1746333708/tkmhibnoafdipri33rby.webm'
    )
    
    Song.objects.create(
        title='Nơi pháo hoa rực rỡ',
        genre=genre,
        duration=208,
        release_date=datetime.date(2022, 1, 1),
        image='https://tse3.mm.bing.net/th?id=OIP.KorsxucNne614rNyuUqPbQAAAA&pid=Api&P=0&h=180',
        audio_url='https://res.cloudinary.com/dneh4yrye/video/upload/v1746502467/pyuvkdn8kf3ydalqdavr.mp3',
        video_url='https://res.cloudinary.com/dneh4yrye/video/upload/v1746502477/hilc8d5ngjcfiqnm0fpg.webm'
    )
    
    Song.objects.create(
        title='Đom đóm',
        genre=genre,
        duration=208,
        release_date=datetime.date(2022, 1, 1),
        image='https://s.meta.com.vn/img/thumb.ashx/Data/image/2020/12/26/loi-bai-hat-dom-dom-jack-1.jpg',
        audio_url='https://res.cloudinary.com/dneh4yrye/video/upload/v1746350887/xjak85x0issl3ieluvkh.mp3',
        video_url='https://res.cloudinary.com/dneh4yrye/video/upload/v1746350892/o8xaxa9k2y4oqjilqz7g.webm'
    )
    
    Song.objects.create(
        title='Sài Gòn đau lòng quá',
        genre=genre,
        duration=208,
        release_date=datetime.date(2022, 1, 1),
        image='https://i.scdn.co/image/ab67616d0000b2736280a70b22a9778115516eb3',
        audio_url='https://res.cloudinary.com/dneh4yrye/video/upload/v1746502583/hvoe0elu20pqsc4jnoz0.mp3',
        video_url='https://res.cloudinary.com/dneh4yrye/video/upload/v1746502591/ft6l3opzmqmseu1oxxc0.webm'
    )
    
    Song.objects.create(
        title='Đường lên phía trước',
        genre=genre,
        duration=208,
        release_date=datetime.date(2022, 1, 1),
        image='https://i.ytimg.com/vi/zX0pOC7y68U/maxresdefault.jpg',
        audio_url='https://res.cloudinary.com/dneh4yrye/video/upload/v1746351075/krnnvxcgh6tqk471xujs.mp3',
        video_url='https://res.cloudinary.com/dneh4yrye/video/upload/v1746351080/zshcn34abnwluhov6yc3.webm'
    )
    
    
class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0008_song_image_alter_song_audio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.RunPython(create_default_songs),

    ]
