# Generated by Django 5.1.6 on 2025-03-09 09:24

import datetime
from django.db import migrations

def create_default_albums(apps, schema_editor):
    Album = apps.get_model('albums', 'Album')

    Album.objects.create(
        title='Sky Tour',
        release_date=datetime.date(2020, 6, 5),
        image='https://tse1.mm.bing.net/th?id=OIP.Vjzs_atJmoBXCCREVZRNtQHaEo&pid=Api&P=0&h=180'
    )
    Album.objects.create(
        title='Mot Cu Lua',
        release_date=datetime.date(2019, 11, 15),
        image='https://tse2.mm.bing.net/th?id=OIP.k7hp0se30lJvb2e2rLyD-wHaE8&pid=Api&P=0&h=180'
    )
    Album.objects.create(
        title='Chúng Ta',
        release_date=datetime.date(2021, 3, 10),
        image='https://mp3indie.com/wp-content/uploads/2024/10/Loi-bai-hat-Di-Ngu-Tang-Duy-Tan-1024x578.jpg'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_rename_artist_id_album_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artist',
        ),
        migrations.RunPython(create_default_albums),
        
    ]
