# Generated by Django 5.1.6 on 2025-03-09 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_rename_artist_id_album_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artist',
        ),
    ]
