# Generated by Django 5.1.6 on 2025-03-10 14:24

from django.db import migrations, models
import datetime


def create_default_artists(apps, schema_editor):
    Artist = apps.get_model("artists", "Artist")
    default_artists = [
        {
            "name": "Noo Phước Thinh",
            "bio": "Ca sĩ nhạc pop nổi tiếng của Việt Nam.",
            "country": "Việt Nam",
            "date_of_birth": datetime.date(1994, 7, 5),
            "image": "https://vnn-imgs-f.vgcloud.vn/2020/10/30/08/noo-phuoc-thinh-toi-luon-ly-tri-trong-chuyen-tinh-cam-1.jpg",
        },
        {
            "name": "Bùi Anh Tuấn",
            "bio": "Rapper nổi tiếng với phong cách trữ tình.",
            "country": "Việt Nam",
            "date_of_birth": datetime.date(1989, 5, 13),
            "image": "https://2sao.vietnamnetjsc.vn/images/2023/06/05/17/07/bui-anh-tuan-3.jpg",
        },
        {
            "name": "Sơn Tùng MTP",
            "bio": "Ca sĩ với giọng ca nội lực và sự nghiệp lâu dài.",
            "country": "Việt Nam",
            "date_of_birth": datetime.date(1981, 1, 16),
            "image": "https://www.thefamousbirthdays.com/photo/2020/06/son_tung_m_tp_1_282017_29_72301a2f_large.jpg",
        },
        {
            "name": "Anh Tú",
            "bio": "Ca sĩ với giọng ca nội lực và sự nghiệp lâu dài.",
            "country": "Việt Nam",
            "date_of_birth": datetime.date(1981, 1, 16),
            "image": "https://res.cloudinary.com/dneh4yrye/image/upload/v1746077775/jqoplu4cgxbxeyhlm4zd.jpg",
        },
        {
            "name": "Quốc Thiên",
            "bio": "Ca sĩ với giọng ca nội lực và sự nghiệp lâu dài.",
            "country": "Việt Nam",
            "date_of_birth": datetime.date(1981, 1, 16),
            "image": "https://yt3.ggpht.com/a-/AAuE7mDjwajH3FmG_NUsrV_q-7AEnE4tGa5i7dXhrg=s900-mo-c-c0xffffffff-rj-k-no",
        },
        {
            "name": "Erik",
            "bio": "Ca sĩ với giọng ca nội lực và sự nghiệp lâu dài.",
            "country": "Việt Nam",
            "date_of_birth": datetime.date(1981, 1, 16),
            "image": "https://tse1.mm.bing.net/th?id=OIP.oGXQz2v2fmU6ZFUyFIHnZQHaEG&pid=Api&P=0&h=180",
        },
        {
            "name": "Quân AP",
            "bio": "Ca sĩ với giọng ca nội lực và sự nghiệp lâu dài.",
            "country": "Việt Nam",
            "date_of_birth": datetime.date(1981, 1, 16),
            "image": "https://static2.yan.vn/YanNews/2167221/201906/hot-boy-cover-quan-ap-la-ai-57d0aa6e.jpg",
        },
    ]
    for artist in default_artists:
        Artist.objects.create(**artist)


class Migration(migrations.Migration):

    dependencies = [
        ("artists", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="image",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(create_default_artists),
    ]
