# Generated by Django 5.1.6 on 2025-03-10 14:24

from django.db import migrations, models
import datetime


def create_default_artists(apps, schema_editor):
    Artist = apps.get_model("artists", "Artist")
    default_artists = [
        {
            "name": "Bùi Anh Tuấn",
            "bio": "Rapper nổi tiếng với phong cách trữ tình.",
            "country": "Việt Nam",
            "date_of_birth": datetime.date(1989, 5, 13),
            "image": "https://2sao.vietnamnetjsc.vn/images/2023/06/05/17/07/bui-anh-tuan-3.jpg",
        },
        {
            "name": "Sơn Tùng MTP",
            "bio": "Ca sĩ với giọng ca nội lực và sự nghiệp lâu dài.",
            "country": "Việt Nam",
            "date_of_birth": datetime.date(1981, 1, 16),
            "image": "https://www.thefamousbirthdays.com/photo/2020/06/son_tung_m_tp_1_282017_29_72301a2f_large.jpg",
        },
        {
            "name": "Anh Tú",
            "bio": "Ca sĩ với giọng ca nội lực và sự nghiệp lâu dài.",
            "country": "Việt Nam",
            "date_of_birth": datetime.date(1981, 1, 16),
            "image": "https://res.cloudinary.com/dneh4yrye/image/upload/v1746077775/jqoplu4cgxbxeyhlm4zd.jpg",
        },
        {
            "name": "Erik",
            "bio": "Ca sĩ với giọng ca nội lực và sự nghiệp lâu dài.",
            "country": "Việt Nam",
            "date_of_birth": datetime.date(1981, 1, 16),
            "image": "https://tse1.mm.bing.net/th?id=OIP.oGXQz2v2fmU6ZFUyFIHnZQHaEG&pid=Api&P=0&h=180",
        },
        {
            "name": "Tiến Minh",
            "bio": "Ca sĩ nhạc pop nổi tiếng của Việt Nam.",
            "country": "Việt Nam",
            "date_of_birth": datetime.date(1994, 7, 5),
            "image": "https://ngoisao.net.vn/uploads/images/2023/05/18/z4356507367716-109aa1126468ae7bb18fedf70159b1f8-1-1684415547.jpg",
        },
        {
            "name": "Min",
            "bio": "Ca sĩ nhạc pop nổi tiếng của Việt Nam.",
            "country": "Việt Nam",
            "date_of_birth": datetime.date(1994, 7, 5),
            "image": "https://tse1.mm.bing.net/th?id=OIP.ITEfGHLLjNucpqJMuqehHwHaEm&pid=Api&P=0&h=180",
        },
        {
            "name": "Jack",
            "bio": "Ca sĩ nhạc pop nổi tiếng của Việt Nam.",
            "country": "Việt Nam",
            "date_of_birth": datetime.date(1994, 7, 5),
            "image": "https://tse4.mm.bing.net/th?id=OIP.j_hWiTubD5pkxtoNJ3P-MAHaE8&pid=Api&P=0&h=180",
        },
        {
            "name": "Đen Vâu",
            "bio": "Ca sĩ nhạc pop nổi tiếng của Việt Nam.",
            "country": "Việt Nam",
            "date_of_birth": datetime.date(1994, 7, 5),
            "image": "https://tse4.mm.bing.net/th?id=OIP.9JZ9_0PAzajmC7Jq1PHuFwHaEK&pid=Api&P=0&h=180",
        },
        {
            "name": "Dương Domic",
            "bio": "Ca sĩ nhạc pop nổi tiếng của Việt Nam.",
            "country": "Việt Nam",
            "date_of_birth": datetime.date(1994, 7, 5),
            "image": "https://tse2.mm.bing.net/th?id=OIP.mcPC-Ot2BvxsvYdCitXQyAHaD4&pid=Api&P=0&h=180",
        },
        {
            "name": "Tùng Dương",
            "bio": "Ca sĩ nhạc pop nổi tiếng của Việt Nam.",
            "country": "Việt Nam",
            "date_of_birth": datetime.date(1994, 7, 5),
            "image": "https://toquoc.mediacdn.vn/280518851207290880/2022/10/4/td25251-16648521244081155929666.jpg",
        },
        {
            "name": "Bon Nghiêm",
            "bio": "Ca sĩ nhạc pop nổi tiếng của Việt Nam.",
            "country": "Việt Nam",
            "date_of_birth": datetime.date(1994, 7, 5),
            "image": "https://i.ytimg.com/vi/rGZ6yqDeyPE/maxresdefault.jpg",
        },
        {
            "name": "Hứa Kim Tuyền",
            "bio": "Ca sĩ nhạc pop nổi tiếng của Việt Nam.",
            "country": "Việt Nam",
            "date_of_birth": datetime.date(1994, 7, 5),
            "image": "https://trixie.com.vn/media/images/article/12534678/c7a6fc41036b2367ef8767523585de28.jpg",
        },
        {
            "name": "Orange",
            "bio": "Ca sĩ nhạc pop nổi tiếng của Việt Nam.",
            "country": "Việt Nam",
            "date_of_birth": datetime.date(1994, 7, 5),
            "image": "https://tse1.mm.bing.net/th?id=OIP.IEOfvkwPei_MUwUSTtbjwwHaE7&pid=Api&P=0&h=180",
        },
        {
            "name": "Hồ Quang Hiếu",
            "bio": "Ca sĩ nhạc pop nổi tiếng của Việt Nam.",
            "country": "Việt Nam",
            "date_of_birth": datetime.date(1994, 7, 5),
            "image": "https://tse4.mm.bing.net/th?id=OIP.qmrpfTKoCKVNLy_JO91ougHaEc&pid=Api&P=0&h=180",
        },
    ]
    for artist in default_artists:
        Artist.objects.create(**artist)


class Migration(migrations.Migration):

    dependencies = [
        ("artists", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="image",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(create_default_artists),
    ]
