# Generated by Django 5.1.7 on 2025-03-21 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0003_rename_user_id_playlist_user'),
        ('songs_playlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songplaylist',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_song', to='playlists.playlist'),
        ),
    ]
