# Generated by Django 5.1.6 on 2025-05-05 01:00

from django.db import migrations, models
import random
import datetime
from django.utils.timezone import now
def create_sample_listening_histories(apps, schema_editor):
    User = apps.get_model("users", "User")
    Song = apps.get_model("songs", "Song")
    ListeningHistory = apps.get_model("listening_histories", "ListeningHistory")

    users = list(User.objects.all())[:3]  # Giả sử có sẵn 3 user
    songs = list(Song.objects.all())[:10]  # Giả sử có sẵn 10 bài hát

    if not users or not songs:
        return  # Không tạo nếu thiếu user hoặc song

    for i in range(10):
        ListeningHistory.objects.create(
            user=random.choice(users),
            song=songs[i % len(songs)],
            played_at=now() - datetime.timedelta(days=i),
            count=random.randint(1, 5)
        )

class Migration(migrations.Migration):

    dependencies = [
        ('listening_histories', '0002_rename_song_id_listeninghistory_song_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeninghistory',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RunPython(create_sample_listening_histories),

    ]
