# Generated by Django 5.1.6 on 2025-05-05 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listening_histories', '0002_rename_song_id_listeninghistory_song_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeninghistory',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
