# Generated by Django 5.1.6 on 2025-03-06 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist_songs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlistsong',
            old_name='playlist_id',
            new_name='playlist',
        ),
        migrations.RenameField(
            model_name='playlistsong',
            old_name='song_id',
            new_name='song',
        ),
    ]
